// Generated by `npm run cf:build`.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- the build artifact does not exist on a fresh checkout
import handler from "../.open-next/worker.js";
import { getToken } from "next-auth/jwt";
import type { NexusCloudflareEnv } from "../lib/cloudflare";
import type { ExecutionContext, Request as WorkerRequest } from "@cloudflare/workers-types";
export { RealtimeHub } from "./realtime-hub";

const methods: Record<string, string> = { socket: "GET", connect: "POST", poll: "GET", event: "POST", disconnect: "POST" };
const worker = {
  async fetch(request: Request, env: NexusCloudflareEnv, ctx: ExecutionContext) {
    const url = new URL(request.url);
    if (url.pathname === "/api/realtime/config") return Response.json({ transport: "cloudflare" });
    const action = url.pathname.startsWith("/api/realtime/") ? url.pathname.slice(14) : "";
    if (!methods[action]) {
      const forwarded = new Headers(request.headers);
      forwarded.set("x-forwarded-host", url.host);
      forwarded.set("x-forwarded-proto", url.protocol.slice(0, -1));
      return handler.fetch(new Request(request, { headers: forwarded }), env, ctx);
    }
    if (request.method !== methods[action]) return new Response("Method not allowed", { status: 405 });
    if ((request.method === "POST" || action === "socket") && request.headers.get("origin") !== url.origin) {
      return new Response("Origin not allowed", { status: 403 });
    }
    if (action === "socket" && request.headers.get("upgrade")?.toLowerCase() !== "websocket") return new Response("WebSocket required", { status: 426 });
    const token = await getToken({ req: request, secret: env.AUTH_SECRET, secureCookie: url.protocol === "https:" });
    if (!token?.sub || !token.exp) return new Response("Unauthorized", { status: 401 });
    const headers = new Headers(request.headers);
    // Never trust identity headers supplied by browsers.
    headers.set("x-nexus-user", token.sub);
    headers.set("x-nexus-expires", String(token.exp * 1000));
    url.pathname = `/${action}`;
    const stub = env.REALTIME.get(env.REALTIME.idFromName("nexus-v1"));
    return stub.fetch(new Request(url, { method: request.method, headers, body: request.body, redirect: "manual" }) as unknown as WorkerRequest);
  },
};
export default worker;
